use std::path::{Path, PathBuf};

use anyhow::{Result, anyhow};
use lazy_static::lazy_static;
use policy_evaluator::{
    ProtocolVersion, evaluation_context::EvaluationContext, policy_evaluator::PolicyExecutionMode,
    policy_evaluator_builder::PolicyEvaluatorBuilder, policy_metadata::Metadata, wasmparser,
};
use semver::{BuildMetadata, Prerelease, Version};

lazy_static! {
    static ref KUBEWARDEN_VERSION: Version = Version::parse(env!("CARGO_PKG_VERSION")).unwrap();
}

pub(crate) enum Backend {
    Opa,
    OpaGatekeeper,
    Wasi,
    KubewardenWapc(ProtocolVersion),
    Ferricel,
}

type KubewardenProtocolDetectorFn = fn(PathBuf) -> Result<ProtocolVersion>;
type RegoDetectorFn = fn(PathBuf) -> Result<bool>;
type FerricelDetectorFn = fn(PathBuf) -> Result<bool>;

// Looks at the Wasm module pointed by `wasm_path` and return whether it was generated by a Rego
// policy
//
// The code looks at the export symbols offered by the Wasm module.
// Having at least one symbol that starts with the `opa_` prefix leads
// the policy to be considered a Rego-based one.
fn rego_policy_detector(wasm_path: PathBuf) -> Result<bool> {
    let data: Vec<u8> = std::fs::read(wasm_path.clone())
        .map_err(|e| anyhow!("cannot access file {:?}: {}", wasm_path, e))?;
    for payload in wasmparser::Parser::new(0).parse_all(&data) {
        if let wasmparser::Payload::ExportSection(s) =
            payload.map_err(|e| anyhow!("cannot parse WebAssembly file: {}", e))?
        {
            for export in s {
                if export
                    .map_err(|e| anyhow!("cannot parse WebAssembly export section: {}", e))?
                    .name
                    .starts_with("opa_")
                {
                    return Ok(true);
                }
            }
        }
    }

    Ok(false)
}

// Looks at the Wasm module pointed by `wasm_path` and returns whether it was produced by ferricel.
//
// The code inspects the WebAssembly `producers` custom section, looking for a `processed-by` field
// that contains an entry named `ferricel`. Ferricel always adds this entry when compiling a CEL
// expression to Wasm.
fn ferricel_policy_detector(wasm_path: PathBuf) -> Result<bool> {
    let data: Vec<u8> = std::fs::read(wasm_path.clone())
        .map_err(|e| anyhow!("cannot access file {:?}: {}", wasm_path, e))?;

    for payload in wasmparser::Parser::new(0).parse_all(&data) {
        let payload = payload.map_err(|e| anyhow!("cannot parse WebAssembly file: {}", e))?;
        if let wasmparser::Payload::CustomSection(cs) = payload
            && let wasmparser::KnownCustom::Producers(reader) = cs.as_known()
        {
            for field in reader {
                let field = field
                    .map_err(|e| anyhow!("cannot parse WebAssembly producers section: {}", e))?;
                if field.name == "processed-by" {
                    for value in field.values {
                        let value = value.map_err(|e| {
                            anyhow!("cannot parse WebAssembly producers field value: {}", e)
                        })?;
                        if value.name == "ferricel" {
                            return Ok(true);
                        }
                    }
                }
            }
        }
    }

    Ok(false)
}

fn kubewarden_protocol_detector(wasm_path: PathBuf) -> Result<ProtocolVersion> {
    let eval_ctx = EvaluationContext::default();
    PolicyEvaluatorBuilder::new()
        .policy_file(&wasm_path)?
        .execution_mode(PolicyExecutionMode::KubewardenWapc)
        .build_pre()?
        .rehydrate(&eval_ctx)?
        .protocol_version()
        .map_err(|e| anyhow!("Cannot compute ProtocolVersion used by the policy: {:?}", e))
}

pub(crate) struct BackendDetector {
    kubewarden_protocol_detector_func: KubewardenProtocolDetectorFn,
    rego_detector_func: RegoDetectorFn,
    ferricel_detector_func: FerricelDetectorFn,
}

impl Default for BackendDetector {
    fn default() -> Self {
        BackendDetector {
            kubewarden_protocol_detector_func: kubewarden_protocol_detector,
            rego_detector_func: rego_policy_detector,
            ferricel_detector_func: ferricel_policy_detector,
        }
    }
}

impl BackendDetector {
    #[allow(dead_code)]
    /// This method is intended to be used by unit tests
    pub(crate) fn new(
        rego_detector_func: RegoDetectorFn,
        kubewarden_protocol_detector_func: KubewardenProtocolDetectorFn,
        ferricel_detector_func: FerricelDetectorFn,
    ) -> Self {
        BackendDetector {
            kubewarden_protocol_detector_func,
            rego_detector_func,
            ferricel_detector_func,
        }
    }

    pub(crate) fn is_rego_policy(&self, wasm_path: &Path) -> Result<bool> {
        (self.rego_detector_func)(wasm_path.to_path_buf())
            .map_err(|e| anyhow!("Rego policy type check failure: {}", e))
    }

    pub(crate) fn is_ferricel_policy(&self, wasm_path: &Path) -> Result<bool> {
        (self.ferricel_detector_func)(wasm_path.to_path_buf())
            .map_err(|e| anyhow!("Ferricel policy type check failure: {}", e))
    }

    pub(crate) fn detect(&self, wasm_path: PathBuf, metadata: &Metadata) -> Result<Backend> {
        let is_rego_policy = self.is_rego_policy(&wasm_path)?;
        let is_ferricel_policy = self.is_ferricel_policy(&wasm_path)?;

        match metadata.execution_mode {
            PolicyExecutionMode::Wasi => Ok(Backend::Wasi),
            PolicyExecutionMode::Ferricel => {
                if is_ferricel_policy {
                    Ok(Backend::Ferricel)
                } else {
                    Err(anyhow!(
                        "Wrong value inside of policy's metadata for 'executionMode'. The policy has not been created using ferricel"
                    ))
                }
            }
            PolicyExecutionMode::Opa => {
                if is_rego_policy {
                    Ok(Backend::Opa)
                } else {
                    Err(anyhow!(
                        "Wrong value inside of policy's metadata for 'executionMode'. The policy has not been created using Rego"
                    ))
                }
            }
            PolicyExecutionMode::OpaGatekeeper => {
                if is_rego_policy {
                    Ok(Backend::OpaGatekeeper)
                } else {
                    Err(anyhow!(
                        "Wrong value inside of policy's metadata for 'executionMode'. The policy has not been created using Rego"
                    ))
                }
            }
            PolicyExecutionMode::KubewardenWapc => {
                if is_rego_policy {
                    Err(anyhow!(
                        "Wrong value inside of policy's metadata for 'executionMode'. This policy has been created using Rego"
                    ))
                } else if is_ferricel_policy {
                    Err(anyhow!(
                        "Wrong value inside of policy's metadata for 'executionMode'. This policy has been created using ferricel"
                    ))
                } else {
                    let protocol_version = (self.kubewarden_protocol_detector_func)(wasm_path)
                        .map_err(|e| {
                            anyhow!("Error while detecting Kubewarden protocol version: {:?}", e)
                        })?;
                    Ok(Backend::KubewardenWapc(protocol_version))
                }
            }
        }
    }
}

/// Check if policy server version is compatible with  minimum kubewarden
/// version required by the policy
/// TODO: this should not take an Option
pub fn has_minimum_kubewarden_version(opt_metadata: Option<&Metadata>) -> Result<()> {
    if let Some(metadata) = opt_metadata
        && let Some(minimum_kubewarden_version) = &metadata.minimum_kubewarden_version
    {
        let sanitized_minimum_kubewarden_version = Version {
            major: minimum_kubewarden_version.major,
            minor: minimum_kubewarden_version.minor,
            // Kubewarden stack version ignore patch version number
            patch: 0,
            pre: Prerelease::EMPTY,
            build: BuildMetadata::EMPTY,
        };
        #[allow(clippy::to_string_in_format_args)]
        if *KUBEWARDEN_VERSION < sanitized_minimum_kubewarden_version {
            return Err(anyhow!(
                "Policy required Kubewarden version {} or greater. But it's running on {}",
                sanitized_minimum_kubewarden_version,
                KUBEWARDEN_VERSION.to_string(),
            ));
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use ferricel_core::compiler::Builder as CompilerBuilder;
    use rstest::rstest;
    use tempfile::NamedTempFile;

    use super::*;

    fn mock_protocol_version_detector_v1(_wasm_path: PathBuf) -> Result<ProtocolVersion> {
        Ok(ProtocolVersion::V1)
    }

    fn mock_rego_policy_detector_true(_wasm_path: PathBuf) -> Result<bool> {
        Ok(true)
    }

    fn mock_rego_policy_detector_false(_wasm_path: PathBuf) -> Result<bool> {
        Ok(false)
    }

    fn mock_ferricel_policy_detector_true(_wasm_path: PathBuf) -> Result<bool> {
        Ok(true)
    }

    fn mock_ferricel_policy_detector_false(_wasm_path: PathBuf) -> Result<bool> {
        Ok(false)
    }

    fn backend_detector(rego: RegoDetectorFn, ferricel: FerricelDetectorFn) -> BackendDetector {
        BackendDetector::new(rego, mock_protocol_version_detector_v1, ferricel)
    }

    /// Compile a trivial CEL expression and return a temp file containing the wasm bytes.
    /// The resulting module will have a `producers` section with a `ferricel` entry.
    fn ferricel_wasm_file() -> NamedTempFile {
        let wasm_bytes = CompilerBuilder::new()
            .build()
            .compile("1 + 1")
            .expect("failed to compile CEL expression");
        let tmp = NamedTempFile::new().expect("failed to create temp file");
        std::fs::write(tmp.path(), wasm_bytes).expect("failed to write wasm");
        tmp
    }

    /// Build a minimal valid wasm module with no producers section.
    fn non_ferricel_wasm_file() -> NamedTempFile {
        let wasm_bytes = wasm_encoder::Module::new().finish();
        let tmp = NamedTempFile::new().expect("failed to create temp file");
        std::fs::write(tmp.path(), wasm_bytes).expect("failed to write wasm");
        tmp
    }

    #[rstest]
    #[case::ferricel_module(ferricel_wasm_file, true)]
    #[case::non_ferricel_module(non_ferricel_wasm_file, false)]
    fn test_ferricel_policy_detector(
        #[case] wasm_file_fn: fn() -> NamedTempFile, // factory fn producing the wasm fixture
        #[case] expected: bool,                      // expected detection result
    ) {
        let tmp = wasm_file_fn();
        let result = ferricel_policy_detector(tmp.path().to_path_buf());
        assert!(result.is_ok());
        assert_eq!(result.unwrap(), expected);
    }

    #[rstest]
    #[case::kubewarden_mode_with_rego_policy(
        PolicyExecutionMode::KubewardenWapc, // execution_mode
        mock_rego_policy_detector_true,      // rego_detector
        mock_ferricel_policy_detector_false, // ferricel_detector
        false,                               // should_succeed
    )]
    #[case::opa_mode_with_non_rego_policy(
        PolicyExecutionMode::Opa,            // execution_mode
        mock_rego_policy_detector_false,     // rego_detector
        mock_ferricel_policy_detector_false, // ferricel_detector
        false,                               // should_succeed
    )]
    #[case::gatekeeper_mode_with_non_rego_policy(
        PolicyExecutionMode::OpaGatekeeper,  // execution_mode
        mock_rego_policy_detector_false,     // rego_detector
        mock_ferricel_policy_detector_false, // ferricel_detector
        false,                               // should_succeed
    )]
    #[case::ferricel_mode_with_ferricel_policy(
        PolicyExecutionMode::Ferricel,       // execution_mode
        mock_rego_policy_detector_false,     // rego_detector
        mock_ferricel_policy_detector_true,  // ferricel_detector
        true,                                // should_succeed
    )]
    #[case::ferricel_mode_with_non_ferricel_policy(
        PolicyExecutionMode::Ferricel,       // execution_mode
        mock_rego_policy_detector_false,     // rego_detector
        mock_ferricel_policy_detector_false, // ferricel_detector
        false,                               // should_succeed
    )]
    #[case::kubewarden_mode_with_ferricel_policy(
        PolicyExecutionMode::KubewardenWapc, // execution_mode
        mock_rego_policy_detector_false,     // rego_detector
        mock_ferricel_policy_detector_true,  // ferricel_detector
        false,                               // should_succeed
    )]
    fn test_backend_detection(
        #[case] execution_mode: PolicyExecutionMode,
        #[case] rego_detector: RegoDetectorFn,
        #[case] ferricel_detector: FerricelDetectorFn,
        #[case] should_succeed: bool,
    ) {
        let metadata = Metadata {
            execution_mode,
            ..Default::default()
        };
        let detector = backend_detector(rego_detector, ferricel_detector);
        let result = detector.detect(PathBuf::from("irrelevant.wasm"), &metadata);
        assert_eq!(result.is_ok(), should_succeed);
    }
}
